spring:
    application:
        name: Nexum's Catalog
    profiles:
        active: local

app:
    name: "Microservicio de Cat치logo"
    version: 0.0.1
    description: "Microservicio de Cat치logo de Nexum, para administrar informaci칩n est치tica"